const STORE = {
  shops: [
    { id: 1,
      store_name: 'Gongcha',
    },
    { id: 2,
      store_name: 'Sharetea',
    },
    { id: 3,
      store_name: 'Tea Top',
    },
    { id: 4,
      store_name: 'Kung Fu Tea',
    },
    { id: 5,
      store_name: '7 Leaves Cafe',
    },
    { id: 6,
      store_name: 'The Teahouse Tapioca & Tea',
    },
    { id: 7,
      store_name: 'Tiger Sugar',
    },
  ],
  drinks: [
    { id: 701,
      drink_name: 'Brown Sugar Boba Milk with Cream Mousse',
      store_id: 7,
    },
    { id: 201,
      drink_name: 'Okinawa Milk Tea',
      store_id: 2,
    },
    { id: 501,
      drink_name: 'Japanese Matcha Soy Tea',
      store_id: 5,
    },
    { id: 202,
      drink_name: 'Mango Green Tea',
      store_id: 2,
    },
    { id: 203,
      drink_name: 'Kiwi Fruit Tea with Aiyu Jelly',
      store_id: 2,
    },
  ]
}