const STORE = {
  shops: [
    { id: 1,
      store_name: 'Gongcha',
      city: 'Houston',
      average_rating: 3.75,
    },
    { id: 2,
      store_name: 'Sharetea',
      city: 'Houston',
      average_rating: 4.35,
    },
    { id: 3,
      store_name: 'Tea Top',
      city: 'Houston',
      average_rating: 3.85,
    },
    { id: 4,
      store_name: 'Kung Fu Tea',
      city: 'Houston',
      average_rating: 3.25,
    },
    { id: 5,
      store_name: '7 Leaves Cafe',
      city: 'Houston',
      average_rating: 4.55,
    },
    { id: 6,
      store_name: 'The Teahouse Tapioca & Tea',
      city: 'Houston',
      average_rating: 3.10,
    },
    { id: 7,
      store_name: 'Tiger Sugar',
      city: 'Houston',
      average_rating: 4.25,
    },
  ],
  drinks: [
    { id: 701,
      drink_name: 'Brown Sugar Boba Milk with Cream Mousse',
      store_id: 7,
      average_rating: 4.35,
    },
    { id: 201,
      drink_name: 'Okinawa Milk Tea',
      store_id: 2,
      average_rating: 4.25,
    },
    { id: 501,
      drink_name: 'Japanese Matcha Soy Tea',
      store_id: 5,
      average_rating: 4.35,
    },
    { id: 202,
      drink_name: 'Mango Green Tea',
      store_id: 2,
      average_rating: 4.45,
    },
    { id: 203,
      drink_name: 'Kiwi Fruit Tea with Aiyu Jelly',
      store_id: 2,
      average_rating: 4.26,
    },
    { id: 204,
      drink_name: 'Taro Pearl Milk Tea',
      store_id: 2,
      average_rating: 4.34,
    },
    { id: 205,
      drink_name: 'Matcha Red Bean Milk Tea',
      store_id: 2,
      average_rating: 4.52,
    },
    { id: 206,
      drink_name: 'QQ Happy Family Milk Tea',
      store_id: 2,
      average_rating: 4.74,
    },
    { id: 207,
      drink_name: 'Peach Kiwi Tea with Aiyu Jelly',
      store_id: 2,
      average_rating: 4.34,
    },
    { id: 208,
      drink_name: 'Wintermelon Lemonade',
      store_id: 2,
      average_rating: 3.91,
    },
    { id: 209,
      drink_name: 'Lime Mojito',
      store_id: 2,
      average_rating: 3.56,
    },
    { id: 210,
      drink_name: 'Thai Tea Ice Blended with Pearl',
      store_id: 2,
      average_rating: 4.23,
    },
  ]
}

export default STORE;